{
  "formatVersion": "1.1",
  "component": {
    "group": "top.girlkisser",
    "module": "cygnus",
    "version": "1.0.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cygnus-1.0.0+1.21.1.jar",
          "url": "cygnus-1.0.0+1.21.1.jar",
          "size": 235610,
          "sha512": "081aebb352e8004d74478b186aec7adff0ac8fff04e9c96e91e747b25d50202c2c1159de0a6cbc0527ef9197c077e36966c93401849c3826cf735388c94b0e3e",
          "sha256": "a4aff342f76b99df601f93644cb048b921c7844bd509c5f536e63bda9033add8",
          "sha1": "2d047282d02eb7888bdfd3ffe8713b387478dd20",
          "md5": "fd28d086e57172a59ae945ee87c56197"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.6.0"
          },
          "excludes": [
            {
              "group": "net.neoforged.fancymodloader",
              "module": "loader"
            }
          ]
        },
        {
          "group": "martian",
          "module": "dapper",
          "version": {
            "requires": "1.3-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.18+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "cygnus-1.0.0+1.21.1.jar",
          "url": "cygnus-1.0.0+1.21.1.jar",
          "size": 235610,
          "sha512": "081aebb352e8004d74478b186aec7adff0ac8fff04e9c96e91e747b25d50202c2c1159de0a6cbc0527ef9197c077e36966c93401849c3826cf735388c94b0e3e",
          "sha256": "a4aff342f76b99df601f93644cb048b921c7844bd509c5f536e63bda9033add8",
          "sha1": "2d047282d02eb7888bdfd3ffe8713b387478dd20",
          "md5": "fd28d086e57172a59ae945ee87c56197"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cygnus-1.0.0+1.21.1-sources.jar",
          "url": "cygnus-1.0.0+1.21.1-sources.jar",
          "size": 143845,
          "sha512": "58199e92c67577298e6fbbd52f0fc0c1c386c9344e95b5b7103a5fd9068e225820c7bcb48adb699fb418340288ef4b93d802d4d333954f659905fc4da71f0470",
          "sha256": "f0244f00806291d3d00ee67bd13598a457c36a3fb8e45103e05bfb5be5324709",
          "sha1": "96f517df42fd79299022460fd8c7c169bc243c03",
          "md5": "bfe5ef85062fba1bb966a2dd1727ab91"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cygnus-1.0.0+1.21.1-javadoc.jar",
          "url": "cygnus-1.0.0+1.21.1-javadoc.jar",
          "size": 467101,
          "sha512": "2d772a742a76c4a9c79446e59799e0b3e68c81040cbe3a8e593178b464dc98e3c6986534dbe3417c580c528f26696e55c006125b5339cfca8d9110feadf9b480",
          "sha256": "5010d32d4297360afc3171c8ffedc1d1fe0091ae8f02b223f3c6950964c47829",
          "sha1": "84e0478199a5f1eae8e64bc216365406e3d3998c",
          "md5": "7f7359fef60488adb3622e5fcdf25255"
        }
      ]
    }
  ]
}
